### PR TITLE
feat: ask for TXT records only

### PR DESCRIPTION
**Pull request by sixcorners**
This builds on #25 and implements the change from #26.

### CODE REVIEW

**Comment by sixcorners** [comment]
The only commit in this pull request that isn't also in #25 is https://github.com/ipfs-shipyard/dnslink-cloudflare/pull/27/commits/8a69af1d860138cdfda0655fc05ea3b3d4d84e71.

**Comment by hacdias** [comment]
@sixcorners could you just rebase on top of master and I can merge it afterwards. Thank you once again!

**Comment by sixcorners** [comment]
@hacdias done

**Comment by hacdias** [comment]
Thanks!

**Comment by sixcorners** [comment]
thank you

**Pull request merged**
