### PR TITLE
fix: handle dnsRecords.browse() pagination

### LINKED ISSUE #23: Paginate through records
If you have more than 20 records then this probably won't find the dnslink TXT record. This should perform pagination to check all records.

### PR DESCRIPTION
**Pull request by sixcorners**
Fixes #23

### CODE REVIEW

**Comment by sixcorners** [comment]
Would it be a good idea to increase the page size to 100?

**Comment by sixcorners** [comment]
Documentation for this is here: cloudflare/node-cloudflare#34 and cloudflare/node-cloudflare#37
... kind of

**Comment by sixcorners** [comment]
I put the pagination code into a new function.
Not even sure what version of node is needed now.

I felt I needed to do this because I couldn't actually test out the pagination for the zones. I don't have 20 zones.

**Comment by sixcorners** [comment]
Hmm. I've gotten that complaint before. I'll have to learn to use @ more.

**Comment by sixcorners** [comment]
@hacdias Just wondering.. is there ever any concern that I might be using a javascript feature that's too new?

**Comment by hacdias** [comment]
I guess it depends on the package. We did not define a minimum Node.js support version on this package. But if you're talking about to the async generators, it should be ok!

**Comment by sixcorners** [comment]
k thanks

**Pull request merged**
